#define GIZA_LEFT_CLICK 'A'

#define GIZA_LS_SOLID      1
#define GIZA_LS_LONG_DASH  2
#define GIZA_LS_SHORT_DASH 3
#define GIZA_LS_DOT        4
#define GIZA_LS_DASH_DOT   5
#define GIZA_LS_DASH_DOT_DOT_DOT 6

#define GIZA_NUMBER_FORMAT_AUTO 0
#define GIZA_NUMBER_FORMAT_DEC  1
#define GIZA_NUMBER_FORMAT_EXP  2

#define GIZA_UNITS_NORMALIZED 0
#define GIZA_UNITS_INCHES 1
#define GIZA_UNITS_MM 2
#define GIZA_UNITS_DEVICE 3
#define GIZA_UNITS_WORLD 4
